spring.application.name=lp32025

# H2 Configuration for a file-based database
spring.datasource.url=jdbc:h2:file:./db/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console (optional, but recommended)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate auto DDL (crear/actualizar tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update

# Habilita el batching de sentencias de JDBC
spring.jpa.properties.hibernate.jdbc.batch_size=100

# Deshabilita la ordenación para que Hibernate pueda usar el batching
spring.jpa.properties.hibernate.order_inserts=false
spring.jpa.properties.hibernate.order_updates=false

# Para ver si funciona el batching
spring.jpa.show-sql=true
